// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvs0Zckq5gJe_Fmbt7G6zzEssn4LZr4Io',
    appId: '1:612109757208:web:8f5cda756779f02a290c6d',
    messagingSenderId: '612109757208',
    projectId: 'daily-vachan-62464',
    authDomain: 'daily-vachan-62464.firebaseapp.com',
    storageBucket: 'daily-vachan-62464.firebasestorage.app',
    measurementId: 'G-662FQC960Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVUQyBLCqz7AmCGUK_WQ1t6BFnVrG4eI',
    appId: '1:612109757208:android:8916b9d334e01cce290c6d',
    messagingSenderId: '612109757208',
    projectId: 'daily-vachan-62464',
    storageBucket: 'daily-vachan-62464.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi1vVamEZIszfL09cwQtvG0laSp41PByg',
    appId: '1:612109757208:ios:4e93365fb609c34d290c6d',
    messagingSenderId: '612109757208',
    projectId: 'daily-vachan-62464',
    storageBucket: 'daily-vachan-62464.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi1vVamEZIszfL09cwQtvG0laSp41PByg',
    appId: '1:612109757208:ios:4e93365fb609c34d290c6d',
    messagingSenderId: '612109757208',
    projectId: 'daily-vachan-62464',
    storageBucket: 'daily-vachan-62464.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvs0Zckq5gJe_Fmbt7G6zzEssn4LZr4Io',
    appId: '1:612109757208:web:562bac7f05b6df90290c6d',
    messagingSenderId: '612109757208',
    projectId: 'daily-vachan-62464',
    authDomain: 'daily-vachan-62464.firebaseapp.com',
    storageBucket: 'daily-vachan-62464.firebasestorage.app',
    measurementId: 'G-2HN3SMHFPH',
  );
}
